### ISSUE TITLE
Version 1.2.8 popup display issue

### ISSUE THREAD

**Issue by Cade66** [igorlogius/localstorage-editor#3]
Hi,

Just updated LSE to 1.2.8, no Release Notes so I was wondering what the new version was all about. No idea but I do notice that the popup display is now problematic ; its height is now fixed and clicking on a L or S or value is hard to read. What happened? What's the update about? Ver. 1.2.7 was just fine IMO ...
Thanks for your work, but I linger to understand what improvement may have led to this static popup ... :=)

**Version 1.2.7:**

![127](https://user-images.githubusercontent.com/65161029/200431538-daf8489e-7aaa-470a-b461-5cb4e9ab4316.png)

**Version 1.2.8:**

![128](https://user-images.githubusercontent.com/65161029/200431585-2f05919f-e7da-475b-94e3-da03d565f15f.png)

**Comment by igorlogius** [comment]
Thanks for letting me know about this regression. 

I got a review on AMO, which notified me about the non functional import button,  but i also made a couple of other minor changes that i hope will improve the usability a little. 

Release notes can be found on the releases pages: https://github.com/igorlogius/localstorage-editor/releases 

The issue with the height should be fixed in the next release. 
Sorry for the trouble.

**Comment by Cade66** [comment]
I read the review you mention just after writing my above comment! I understand now.
Acknowledging as well the availability of LSE"s release Notes at https://github.com/igorlogius/localstorage-editor/releases
No big issue, a slight bother... given I use the extension quite... extensively. I hadn't noticed the import issue because I haven't used it until now. Fix is welcomed of course.
